apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          volumeMounts:
            - name: minio-data
              mountPath: /data
          ports:
            - containerPort: 9000
              name: backend
            - containerPort: 9001
              name: console
          env:
            - name: MINIO_ROOT_USER
              value: NEOSHOWCASEMINIOROOTUSER
            - name: MINIO_ROOT_PASSWORD
              value: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
      volumes:
        - name: minio-data
          hostPath:
            path: /opt/minio