apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ns-auth

spec:
  forwardAuth:
    address: http://ns-auth.ns-system.svc.cluster.local/
    authResponseHeaders:
      - X-Forwarded-User
