apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ns-auth-dev

spec:
  forwardAuth:
    address: http://ns-auth-dev.ns-system.svc.cluster.local/
    authResponseHeaders:
      - X-Forwarded-User
