apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-chart
  namespace: argocd

spec:
  destination:
    namespace: promtail
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: "6.11.5"
      helm:
        valueFiles:
          - $values/.local-dev/manifest/promtail/values.yaml
    - repoURL: https://github.com/traPtitech/NeoShowcase
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
