apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-apps
  namespace: argocd
spec:
  destination:
    namespace: ns-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/traPtitech/NeoShowcase
    path: .local-dev/manifest/ns-apps
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
