apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-apps
  namespace: argocd
spec:
  destination:
    namespace: ns-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://git.toki317.dev/toki/ns-manifest.git
    path: ns-apps
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: false
      selfHeal: false
