apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd

spec:
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/traPtitech/NeoShowcase
    path: .local-dev/manifest/victoria-metrics
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
