dsn: mariadb://root:password@localhost:5004/neoshowcase
docPath: docs/dbschema
disableOutputSchema: true
er:
  format: mermaid

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
