dsn: mariadb://root:password@localhost:5004/neoshowcase
docPath: docs/dbschema
er:
  format: svg

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true

exclude:
  - migrations
