output = "pkg/infrastructure/repository/models"
wipe = true
no-tests = true

[mysql]
dbname = "neoshowcase"
host = "localhost"
port = 5004
user = "root"
pass = "password"
sslmode = "false"
blacklist = ["migrations"]
