buildkit:
  address: tcp://buildkitd:1234

buildpack:
  backend: docker
  docker:
    containerName: neoshowcase-buildpack-1
    remoteDir: /workspace
    user: cnb
    group: cnb
    platformAPI: "0.11"

repository:
  privateKeyFile: /keys/id_ed25519

controller:
  url: http://ns-controller:10000

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: local
  local:
    dir: /data

image:
  registry:
    scheme: http
    addr: registry.local
    username: ""
    password: ""
  namePrefix: ns-apps/
  tmpNamePrefix: ns-apps-tmp/
