port: 10000
debug: true
privateKeyFile: /keys/id_ed25519
mode: docker

docker:
  confDir: /opt/traefik/conf
  middlewares:
    auth:
      - domain: "*.local.trapti.tech"
        soft:
          - nsapp_auth_soft@file
          - nsapp_auth@file
          # - ns_auth_dev@file
        hard:
          - nsapp_auth_hard@file
          - nsapp_auth@file
          # - ns_auth_dev@file
  ss:
    url: http://ns-ssgen:8080/
  network: neoshowcase_apps
  labels:
    # test additional labels
    - key: neoshowcase.trap.jp/test
      value: ns-apps
  tls:
    certResolver: nsresolver
    wildcard:
      domains: []
  resources:
    cpus: 1.6
    memory: 1000000000 # 1GB
    memorySwap: -1
    memoryReservation: 256000000 # 256MB

ssh:
  port: 2201

webhook:
  basePath: /api/webhook
  port: 8080

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: local
  local:
    dir: /data

image:
  registry:
    scheme: http
    addr: registry.local
    username: ""
    password: ""
  namePrefix: ns-apps/
