port: 8080
debug: true
privateKeyFile: /keys/id_ed25519
avatarBaseURL: https://q.trap.jp/api/v3/public/icon/
authHeader: X-Showcase-User

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

controller:
  url: http://ns-controller:10000

mariadb:
  host: mysql
  port: 3306
  adminUser: root
  adminPassword: password

mongodb:
  host: mongo
  port: 27017
  adminUser: root
  adminPassword: password

storage:
  type: local
  local:
    dir: /data

log:
  type: loki
  loki:
    endpoint: http://loki:3100
    queryTemplate: "{ns_trap_jp_app_id=\"{{ .App.ID }}\"}"

metrics:
  type: prometheus
  prometheus:
    endpoint: http://victoria-metrics:8428
    queries:
      - name: CPU
        template: >-
          rate(container_cpu_user_seconds_total{name="nsapp-{{ .App.ID }}"}[5m])
           + rate(container_cpu_system_seconds_total{name="nsapp-{{ .App.ID }}"}[5m])
      - name: Memory
        template: >-
          container_memory_usage_bytes{name="nsapp-{{ .App.ID }}"}
           + container_memory_swap{name="nsapp-{{ .App.ID }}"}
