port: 8080
debug: true
privateKeyFile: /keys/id_ed25519
avatarBaseURL: https://q.trap.jp/api/v3/public/icon/
authHeader: X-Showcase-User

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

controller:
  url: http://ns-controller:10000

mariadb:
  host: mysql
  port: 3306
  adminUser: root
  adminPassword: password

mongodb:
  host: mongo
  port: 27017
  adminUser: root
  adminPassword: password

storage:
  type: local
  local:
    dir: /data

log:
  type: loki
  loki:
    endpoint: http://loki:3100
    queryTemplate: "{ns_trap_jp_app_id=\"{{ .App.ID }}\"}"

metrics:
  type: prometheus
  prometheus:
    endpoint: http://prometheus:9090
    queries:
      - name: CPU
        template: "TODO"
      - name: Memory
        template: "TODO"
