artifactsRoot: /artifacts
healthPort: 8081

server:
  type: caddy
  caddy:
    adminAPI: http://static-server:2019
    docsRoot: /artifacts

controller:
  url: http://ns-controller:10000

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: local
  local:
    dir: /data
