debug: true

mode: docker

db:
  host: mysql
  port: 3306
  username: root
  password: password
  database: neoshowcase

mariadb:
  host: mysql
  port: 3306
  adminUser: root
  adminPassword: password

mongodb:
  host: mongo
  port: 27017
  adminUser: root
  adminPassword: password

storage:
  type: local
  local:
    dir: /data

docker:
  confDir: /opt/traefik/conf
  ss:
    url: http://ns-ssgen:8080/
  network: neoshowcase_apps
  labels:
    # test additional labels
    neoshowcase.trap.jp/test: ns-apps
  tls:
    certResolver: nsresolver
    wildcard:
      domains: []

log:
  type: loki
  loki:
    endpoint: http://loki:3100
    appIDLabel: neoshowcase_trap_jp_appId

web:
  app:
    port: 5000
  component:
    port: 10000

repository:
  privateKeyFile: /keys/id_ed25519

image:
  registry:
    scheme: http
    addr: registry.local.trapti.tech
    username: ""
    password: ""
    namePrefix: ns-apps/
