global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: ^(private\.|)([^:]+):.+
        replacement: ${2}
