apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-ssgen

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-ssgen
  template:
    metadata:
      labels:
        app: ns-ssgen
    spec:
      containers:
        - name: ns-ssgen
          image: ghcr.io/traptitech/ns-ssgen:main
          imagePullPolicy: Never
          args:
            - run
            - --loglevel=debug
            - --config=/opt/config/config.yaml
          volumeMounts:
            - mountPath: /artifacts
              name: artifacts
            - mountPath: /opt/config/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /keys
              name: keys
          ports:
            - containerPort: 80
              name: http
            - containerPort: 8081
              name: probe
          startupProbe:
            httpGet:
              port: probe
              path: /healthz
            periodSeconds: 1
            failureThreshold: 300
          readinessProbe:
            httpGet:
              port: probe
              path: /healthz
            periodSeconds: 1
            failureThreshold: 60
          livenessProbe:
            httpGet:
              port: probe
              path: /healthz
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: artifacts
          emptyDir: {}
        - name: config
          configMap:
            name: ns-config
            items:
              - key: ns-ssgen.yaml
                path: config.yaml
        - name: keys
          secret:
            secretName: ns-keys
