apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ns-ssh

spec:
  entryPoints:
    - ns-ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - namespace: ns-system
          name: ns-controller
          port: 2201
          weight: 1
