apiVersion: v1
kind: ConfigMap
metadata:
  name: neoshowcase
  namespace: neoshowcase
data:
  AdminDBHost: mariadb
  AdminDBUser: root
  AdminDBPassword: password
  AdminDBName: neoshowcase
  ImageRegistoryHost: registry.dev.wtks.work
