apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: neoshowcase
  labels:
    app: db-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/traptitech/ns-migrate:master
          command:
            - ./ns-migrate
            - up
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: AdminDBHost
                  name: neoshowcase
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: AdminDBName
                  name: neoshowcase
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: AdminDBUser
                  name: neoshowcase
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: AdminDBPassword
                  name: neoshowcase
      restartPolicy: Never
