apiVersion: v1
kind: Service
metadata:
  name: staticsite
  namespace: neoshowcase
  labels:
    app: staticsite
spec:
  ports:
    - port: 10000
      targetPort: grpc
      name: grpc
    - port: 80
      targetPort: http
      name: http
  clusterIP: None
  selector:
    app: staticsite
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: staticsite
    neoshowcase.trap.jp/component-type: "ssgen"
  name: staticsite
  namespace: neoshowcase
spec:
  serviceName: staticsite
  replicas: 1
  selector:
    matchLabels:
      app: staticsite
      neoshowcase.trap.jp/component-type: "ssgen"
  template:
    metadata:
      labels:
        app: staticsite
        neoshowcase.trap.jp/component-type: "ssgen"
    spec:
      containers:
        - name: caddy
          image: caddy:2.2.1-alpine
          command:
            - caddy
            - run
            - --resume
          volumeMounts:
            - mountPath: /artifacts
              name: artifacts
          ports:
            - containerPort: 80
              name: http
        - name: ssgen
          image: ghcr.io/traptitech/ns-ssgen:master
          imagePullPolicy: Always
          env:
            - name: NS_SSGEN_SERVER
              value: caddy
            - name: NS_SSGEN_ARTIFACTSROOT
              value: /artifacts
            - name: NS_SSGEN_CADDY_ADMINENDPOINT
              value: http://127.0.0.1:2019
            - name: NS_SSGEN_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: AdminDBHost
                  name: neoshowcase
            - name: NS_SSGEN_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: AdminDBUser
                  name: neoshowcase
            - name: NS_SSGEN_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AdminDBPassword
                  name: neoshowcase
            - name: NS_SSGEN_DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: AdminDBName
                  name: neoshowcase
            - name: NS_SSGEN_STORAGE_TYPE
              value: "s3"
            - name: NS_SSGEN_STORAGE_S3_BUCKET
              value: "neoshowcase"
            - name: NS_SSGEN_STORAGE_S3_ACCESSKEY
              valueFrom:
                configMapKeyRef:
                  key: S3AccessKey
                  name: neoshowcase
            - name: NS_SSGEN_STORAGE_S3_ACCESSSECRET
              valueFrom:
                configMapKeyRef:
                  key: S3AccessSecret
                  name: neoshowcase
            - name: NS_SSGEN_STORAGE_S3_REGION
              value: us-east-1
            - name: NS_SSGEN_STORAGE_S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: S3Endpoint
                  name: neoshowcase
          volumeMounts:
            - mountPath: /artifacts
              name: artifacts
          ports:
            - containerPort: 10000
              name: grpc
      volumes:
        - name: artifacts
          emptyDir: { }
