apiVersion: v1
kind: Service
metadata:
  name: mc
  namespace: neoshowcase
  labels:
    app: mc
spec:
  ports:
    - port: 8081
      targetPort: http
  clusterIP: None
  selector:
    app: mc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc
  name: mc
  namespace: neoshowcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - name: mc
          image: ghcr.io/traptitech/ns-mc:master
          ports:
            - containerPort: 8081
              name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: neoshowcase
  name: apiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neoshowcase-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    namespace: neoshowcase
    name: apiserver
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: neoshowcase
  labels:
    app: apiserver
spec:
  ports:
    - port: 80
      targetPort: http
  clusterIP: None
  selector:
    app: apiserver
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apiserver
  namespace: neoshowcase
  labels:
    app: apiserver
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
    - host: dev.wtks.work
      http:
        paths:
          - backend:
              serviceName: apiserver
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: neoshowcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      serviceAccountName: apiserver
      containers:
        - name: apiserver
          image: ghcr.io/traptitech/ns:master
          imagePullPolicy: Always
          env:
            - name: NS_APISERVER_MODE
              value: k8s
            - name: NS_APISERVER_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: AdminDBHost
                  name: neoshowcase
            - name: NS_APISERVER_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: AdminDBUser
                  name: neoshowcase
            - name: NS_APISERVER_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AdminDBPassword
                  name: neoshowcase
            - name: NS_APISERVER_DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: AdminDBName
                  name: neoshowcase
            - name: NS_APISERVER_HTTP_PORT
              value: "8080"
            - name: NS_APISERVER_HTTP_DEBUG
              value: "true"
            - name: NS_APISERVER_SSGEN_ADDR # TODO dynamic discovery
              value: "staticsite-0:10000"
            - name: NS_APISERVER_SSGEN_INSECURE
              value: "true"
            - name: NS_APISERVER_BUILDER_ADDR # TODO dynamic discovery
              value: "builder-0:10000"
            - name: NS_APISERVER_BUILDER_INSECURE
              value: "true"
          ports:
            - containerPort: 8080
              name: http