apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mariadb-migration-template
  generateName: mariadb-migration-

spec:
  entrypoint: run
  templates:
    - name: run
      container:
        name: migrate
        image: ghcr.io/traptitech/ns-migrate:main
        # "Always" in prod
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: MariaDBHost
                name: ns-config
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: MariaDBPort
                name: ns-config
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                key: MariaDBUser
                name: ns-config
          - name: DB_PASS
            valueFrom:
              configMapKeyRef:
                key: MariaDBPassword
                name: ns-config
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                key: MariaDBName
                name: ns-config
