loki:
  # disable multi-tenant
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  readinessProbe:
    initialDelaySeconds: 0
  storage:
    bucketNames:
      admin: loki-admin
      chunks: loki-chunks
      ruler: loki-ruler
    type: s3
    s3:
      endpoint: minio.ns-system.svc.cluster.local
      region: us-east-1
      accessKeyId: NEOSHOWCASEMINIOROOTUSER
      secretAccessKey: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
      s3ForcePathStyle: true
      insecure: true

singleBinary:
  replicas: 1

# not needed in single binary installation
gateway:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false
