buildkit:
  address: unix:///run/buildkit/buildkitd.sock

buildpack:
  backend: k8s
  k8s:
    namespace: ns-system
    # podName: ns-builder # specified from env
    containerName: buildpack
    localDir: /neoshowcase/buildpack
    remoteDir: /workspace
    user: 1000
    group: 1000

repository:
  privateKeyFile: /keys/id_ed25519

controller:
  url: http://ns-controller.ns-system.svc.cluster.local:10000

db:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    accessKey: NEOSHOWCASEMINIOROOTUSER
    accessSecret: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
    region: us-east-1
    endpoint: http://minio.ns-system.svc.cluster.local

image:
  registry:
    scheme: http
    addr: registry.ns-system.svc.cluster.local
    username: ""
    password: ""
  namePrefix: ns-apps/
