port: 10000
debug: false
mode: k8s

db:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    accessKey: NEOSHOWCASEMINIOROOTUSER
    accessSecret: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
    region: us-east-1
    endpoint: http://minio.ns-system.svc.cluster.local

k8s:
  middlewares:
    auth:
      - domain: "*.local.trapti.tech"
        soft:
          - nsapp_auth_soft@file
          - nsapp_auth@file
        hard:
          - nsapp_auth_hard@file
          - nsapp_auth@file
  ss:
    namespace: ns-system
    kind: Service
    name: ns-ssgen
    port: 80
  namespace: ns-apps
  # extra labels
  labels:
    - key: app.kubernetes.io/instance
      value: ns-apps
  tls:
    type: traefik
    traefik:
      certResolver: resolver
      wildcard:
        domains: []
  # required if registry is private
  imagePullSecret: ""
  resources:
    requests:
      cpu: 50m
      memory: 50M
    limits:
      cpu: 1600m
      memory: 1G

repository:
  privateKeyFile: /keys/id_ed25519

image:
  registry:
    scheme: http
    addr: registry.ns-system.svc.cluster.local
    username: ""
    password: ""
  namePrefix: ns-apps/
