port: 10000
debug: false
privateKeyFile: /keys/id_ed25519
mode: k8s

k8s:
  domains:
    - domain: "*.local.trapti.tech"
      excludes: []
      auth:
        available: true
        soft:
          - name: nsapp-auth-soft
            namespace: ns-apps
          - name: nsapp-auth
            namespace: ns-apps
        hard:
          - name: nsapp-auth-hard
            namespace: ns-apps
          - name: nsapp-auth
            namespace: ns-apps
  ports:
    - startPort: 39000
      endPort: 39999
      protocol: tcp
    - startPort: 39000
      endPort: 39999
      protocol: udp
  ss:
    namespace: ns-system
    kind: Service
    name: ns-ssgen
    port: 80
    scheme: http
  namespace: ns-apps
  # extra labels
  labels:
    - key: app.kubernetes.io/instance
      value: ns-apps
  tls:
    type: traefik
    traefik:
      certResolver: resolver
      wildcard:
        domains: []
  # required if registry is private
  imagePullSecret: ""
  resources:
    requests:
      cpu: 10m
      memory: 50M
    limits:
      cpu: 1600m
      memory: 1G

ssh:
  host: localhost
  port: 2201

webhook:
  basePath: /api/webhook
  port: 8080

db:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  username: root
  password: password
  database: neoshowcase

storage:
  type: s3
  s3:
    bucket: neoshowcase
    accessKey: NEOSHOWCASEMINIOROOTUSER
    accessSecret: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
    region: us-east-1
    endpoint: http://minio.ns-system.svc.cluster.local

image:
  registry:
    scheme: http
    addr: registry.ns-system.svc.cluster.local
    username: ""
    password: ""
  namePrefix: ns-apps/
  tmpNamePrefix: ns-apps-tmp/
