port: 8080
debug: false
avatarBaseURL: https://q.trap.jp/api/v3/public/icon/
headerName: X-Showcase-User

controller:
  url: http://ns-controller.ns-system.svc.cluster.local:10000

db:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  username: root
  password: password
  database: neoshowcase

mariadb:
  host: mariadb.ns-system.svc.cluster.local
  port: 3306
  adminUser: root
  adminPassword: password

mongodb:
  host: mongo
  port: 27017
  adminUser: root
  adminPassword: password

storage:
  type: s3
  s3:
    bucket: neoshowcase
    accessKey: NEOSHOWCASEMINIOROOTUSER
    accessSecret: 593fbde300c5718e416886e7e4be339d903541b3900f211ceb89f5b4052a98b3
    region: us-east-1
    endpoint: http://minio.ns-system.svc.cluster.local

log:
  type: loki
  loki:
    endpoint: http://loki.loki.svc.cluster.local:3100
    appIDLabel: neoshowcase_trap_jp_app_id

repository:
  privateKeyFile: /keys/id_ed25519
