name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GO_VERSION: 1.17.7

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
      - run: go mod download
  tools:
    name: Go install tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: go-tools-cache
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-goinstall-${{ env.GO_VERSION }}
      - name: Install dependency modules
        if: steps.go-tools-cache.outputs.cache-hit != 'true'
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
  protoc:
    name: Genarate Code From Proto
    runs-on: ubuntu-latest
    needs: [ tools ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.6.1'
      - uses: actions/cache@v2
        id: go-proto-cache
        with:
          path: ./pkg/interface/grpc/pb
          key: ${{ runner.os }}-proto-${{ hashFiles('**/*.proto') }}
      - uses: actions/cache@v2
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-goinstall-${{ env.GO_VERSION }}
      - name: Generate code
        if: steps.go-proto-cache.outputs.cache-hit != 'true'
        run: make protoc
        env:
          GO_REPO_ROOT_PACKAGE: github.com/traPtitech/neoshowcase
  build:
    name: Build Components
    runs-on: ubuntu-latest
    needs: [ mod, protoc ]
    strategy:
      matrix:
        component:
          - ns
          - ns-builder
          - ns-mc
          - ns-migrate
          - ns-ssgen
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2
        with:
          path: ./pkg/interface/grpc/pb
          key: ${{ runner.os }}-proto-${{ hashFiles('**/*.proto') }}
      - run: go build ./cmd/${{ matrix.component }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [ mod, protoc ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: Install golangci-lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s --  -b $(go env GOPATH)/bin
      - name: Add PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2
        with:
          path: ./pkg/interface/grpc/pb
          key: ${{ runner.os }}-proto-${{ hashFiles('**/*.proto') }}
      - name: golangci-lint
        run: golangci-lint run --out-format=line-number | reviewdog -f=golangci-lint -name=golangci-lint -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ mod, protoc ]
    env:
      ENABLE_DB_TESTS: "true"
      ENABLE_DOCKER_TESTS: "true"
    services:
      mysql:
        image: mysql:8
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=3s --health-retries=10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: neoshowcase
        ports:
          - 5004:3306
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 5010:27017
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2
        with:
          path: ./pkg/interface/grpc/pb
          key: ${{ runner.os }}-proto-${{ hashFiles('**/*.proto') }}
      - name: sql-migrate up
        run: go run ./cmd/ns-migrate up -P 5004
      - name: Run tests
        run: go test ./... -v -race -coverprofile=coverage.out -covermode=atomic -vet=off
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  k8s-test:
    name: Test (k8s)
    runs-on: ubuntu-latest
    needs: [ mod, protoc ]
    env:
      ENABLE_K8S_TESTS: "true"
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: AbsaOSS/k3d-action@v1.5.0
        id: single-cluster
        name: "Create Single Cluster"
        with:
          cluster-name: "test-cluster"
          args: >-
            --agents 1
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"
      - name: Cluster info
        run: |
          echo ${{ steps.single-cluster.outputs.network }} ${{ steps.single-cluster.outputs.subnet-CIDR }}
          echo
          kubectl cluster-info --context k3d-test-cluster
      - name: Nodes
        # hack, wait until agents are ready...
        run: |
          docker ps -a
          sleep 10
          kubectl config use-context k3d-test-cluster
          kubectl get nodes -o wide
          kubectl create ns neoshowcase-apps
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2
        with:
          path: ./pkg/interface/grpc/pb
          key: ${{ runner.os }}-proto-${{ hashFiles('**/*.proto') }}
      - name: Run tests
        run: go test ./pkg/infrastructure/backend/k8simpl -v -coverprofile=coverage.out -covermode=atomic -vet=off
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  tbls:
    name: TBLS
    runs-on: ubuntu-latest
    env:
      TBLS_VERSION: v1.49.6
    services:
      mysql:
        image: mariadb:10.6.4
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: neoshowcase
        ports:
          - 5004:3306
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install sql-migrate
        run: go get -v github.com/rubenv/sql-migrate/...
      - uses: actions/checkout@v2
      - run: sql-migrate up
      - name: Lint
        run: |
          source <(curl -sL https://git.io/use-tbls)
          tbls lint
        env:
          TBLS_DSN: "mariadb://root:password@127.0.0.1:5004/neoshowcase"
  spectral:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral checks
        uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: api/http/swagger.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
