name: master

on:
  push:
    branches:
      - main

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - ns
          - ns-builder
          - ns-mc
          - ns-migrate
          - ns-ssgen
    steps:
      - uses: actions/checkout@v2
      - name: Set APP_VERSION env
        run: echo "APP_VERSION=main-SNAPSHOT" >> $GITHUB_ENV
      - name: Set APP_REVISION env
        run: echo "APP_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{ matrix.component }}
          platforms: linux/amd64
          push: true
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            APP_REVISION=${{ env.APP_REVISION }}
          tags: ghcr.io/traptitech/${{ matrix.component }}:main
